[build]
  command = "make build && yarn build"
  functions = "functions"
  publish = "src"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/HenrikFricke/netlify-blogpost-rating"